# Generated by Django 4.2.6 on 2023-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
