# Generated by Django 4.2.6 on 2023-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, upload_to='user_info/'),
            preserve_default=False,
        ),
    ]
