# Generated by Django 4.2.6 on 2023-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
