# Generated by Django 4.2.6 on 2023-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_main_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main_Date',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='user_info/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
