# Generated by Django 4.2.6 on 2023-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_featured_mainsilder_startslider_delete_navbar_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='info',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
