# Generated by Django 4.2.6 on 2023-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_main_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
