# Generated by Django 4.2.6 on 2023-10-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
