# Generated by Django 4.2.6 on 2023-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_popular_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('you_tube', models.CharField(max_length=255)),
                ('vimeo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('little_info', models.CharField(max_length=255)),
                ('big_info', models.TextField()),
            ],
        ),
    ]
