# Generated by Django 4.2.6 on 2023-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_follow_latest_main_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('button', models.CharField(max_length=255)),
                ('small_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
